/**
 * Initial Default Brokers Data for Database Seeding (All 12 Top Brokers)
 */
export const INITIAL_BROKERS = [
  {
    id: 'exness',
    slug: 'exness',
    name: 'Exness',
    rankNum: 1,
    rank: '#1',
    isFirst: true,
    rating: 4.9,
    reviewsCount: '8.4K reviews',
    trustScore: 99,
    highlightBadge: 'India #1 Pick • Instant UPI',
    badgeTheme: 'emerald',
    minDeposit: '₹850 ($10)',
    minDepositINR: 850,
    minDepositUSD: 10,
    spread: 'From 0.0 pips',
    spreadNum: 0.0,
    maxLeverage: '1:Unlimited',
    regulation: 'FCA, CySEC, FSA',
    regulatorsList: ['FCA', 'CySEC', 'FSA'],
    platforms: 'MT4, MT5, Exness App',
    platformsList: ['MT4', 'MT5', 'Mobile App'],
    payments: 'UPI, IMPS, NetBanking, Paytm, Crypto',
    paymentsList: ['UPI', 'NetBanking', 'Crypto'],
    executionType: 'Instant Market Execution',
    accountTypes: 'Standard, Raw Spread, Zero',
    features: ['Instant 24/7 UPI & NetBanking Payouts', 'Zero Commission on Standard', 'USD/INR & Gold Spreads From 0.0', 'No Overnight Swap Fees'],
    pros: ['Instant automated UPI withdrawals within 60 seconds', 'Zero swap fees on major currencies & gold for Indian traders', 'Lowest spreads from 0.0 pips'],
    cons: ['Unlimited leverage requires strict risk management', 'Inactivity fee after 90 days'],
    yearFounded: 2008,
    headquarters: 'Cyprus & Seychelles',
    categories: ['top-rated', 'upi-accepted', 'raw-spread', 'low-deposit', 'high-leverage', 'ecn'],
    websiteUrl: 'https://www.exness.com',
    affiliateUrl: 'https://www.exness.com',
    contactEmail: 'support@exness.com',
    brandColor: '#f59e0b',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'xm',
    slug: 'xm',
    name: 'XM',
    rankNum: 2,
    rank: '#2',
    isFirst: false,
    rating: 4.8,
    reviewsCount: '6.2K reviews',
    trustScore: 98,
    highlightBadge: '₹450 Min. Deposit • ₹2,500 Bonus',
    badgeTheme: 'coral',
    minDeposit: '₹450 ($5)',
    minDepositINR: 450,
    minDepositUSD: 5,
    spread: 'From 0.6 pips',
    spreadNum: 0.6,
    maxLeverage: '1:1000',
    regulation: 'FCA, CySEC, ASIC',
    regulatorsList: ['FCA', 'CySEC', 'ASIC'],
    platforms: 'MT4, MT5, XM App',
    platformsList: ['MT4', 'MT5', 'Mobile App'],
    payments: 'UPI, NetBanking, Google Pay, Cards',
    paymentsList: ['UPI', 'NetBanking', 'Google Pay'],
    executionType: 'STP / DMA',
    accountTypes: 'Micro, Standard, Ultra Low',
    features: ['₹2,500 ($30) Free No-Deposit Bonus', 'Local Indian Bank Transfers', 'Zero Requotes Guaranteed', 'Free Hindi Customer Support'],
    pros: ['Only ₹450 minimum entry for beginners in India', 'Free ₹2,500 trading bonus without deposit', '100% negative balance protection'],
    cons: ['Standard account has 1.0 pip spread', 'No crypto weekend trading'],
    yearFounded: 2009,
    headquarters: 'Cyprus & Australia',
    categories: ['top-rated', 'upi-accepted', 'low-deposit', 'high-leverage', 'mt4-mt5'],
    websiteUrl: 'https://www.xm.com',
    affiliateUrl: 'https://www.xm.com',
    contactEmail: 'support@xm.com',
    brandColor: '#e11d48',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'octa',
    slug: 'octa',
    name: 'Octa',
    rankNum: 3,
    rank: '#3',
    isFirst: false,
    rating: 4.7,
    reviewsCount: '9.1K reviews',
    trustScore: 97,
    highlightBadge: 'Zero Swap • Top Copy Trading',
    badgeTheme: 'blue',
    minDeposit: '₹1,500 ($25)',
    minDepositINR: 1500,
    minDepositUSD: 25,
    spread: 'From 0.6 pips',
    spreadNum: 0.6,
    maxLeverage: '1:1000',
    regulation: 'CySEC, MISA',
    regulatorsList: ['CySEC', 'MISA'],
    platforms: 'OctaTrader, MT4, MT5',
    platformsList: ['OctaTrader', 'MT4', 'MT5'],
    payments: 'UPI, Paytm, PhonePe, IMPS, Crypto',
    paymentsList: ['UPI', 'Paytm', 'PhonePe', 'Crypto'],
    executionType: 'STP',
    accountTypes: 'OctaTrader, MT4, MT5',
    features: ['Award-Winning Copy Trading Community', '100% Free Swap on Major Currencies', 'Fastest UPI & PhonePe Transfers', '50% Deposit Bonus on Every Top-Up'],
    pros: ['Top-rated copy trading platform for beginners', 'Zero overnight swap fees', 'Hindi webinars and customer service'],
    cons: ['Limited stock CFD instruments', 'Offshore entity for non-EU accounts'],
    yearFounded: 2011,
    headquarters: 'Cyprus & St. Vincent',
    categories: ['top-rated', 'upi-accepted', 'copy-trading', 'high-leverage'],
    websiteUrl: 'https://www.octafx.com',
    affiliateUrl: 'https://www.octafx.com',
    contactEmail: 'support@octafx.com',
    brandColor: '#0284c7',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'ic-markets',
    slug: 'ic-markets',
    name: 'IC Markets',
    rankNum: 4,
    rank: '#4',
    isFirst: false,
    rating: 4.9,
    reviewsCount: '5.8K reviews',
    trustScore: 99,
    highlightBadge: 'Lowest Spreads • True ECN',
    badgeTheme: 'emerald',
    minDeposit: '₹16,500 ($200)',
    minDepositINR: 16500,
    minDepositUSD: 200,
    spread: 'From 0.0 pips',
    spreadNum: 0.0,
    maxLeverage: '1:500',
    regulation: 'ASIC, CySEC, FSA, SCB',
    regulatorsList: ['ASIC', 'CySEC', 'FSA'],
    platforms: 'MT4, MT5, cTrader, TradingView',
    platformsList: ['MT4', 'MT5', 'cTrader', 'TradingView'],
    payments: 'NetBanking, Cards, Crypto, Skrill, Neteller',
    paymentsList: ['NetBanking', 'Cards', 'Crypto'],
    executionType: 'True ECN Direct',
    accountTypes: 'Raw Spread, Standard, cTrader',
    features: ['Institutional-Grade Raw Liquidity', 'Average EUR/USD Spread: 0.1 Pips', 'Direct TradingView Integration', 'Fastest Fiber Optic Execution (<35ms)'],
    pros: ['World-renowned lowest spreads for scalpers and algorithmic traders', 'Direct TradingView charts execution', 'ASIC & CySEC Tier-1 security'],
    cons: ['Higher minimum deposit (₹16,500)', 'No instant UPI support currently'],
    yearFounded: 2007,
    headquarters: 'Sydney, Australia',
    categories: ['top-rated', 'raw-spread', 'ecn', 'tradingview', 'mt4-mt5'],
    websiteUrl: 'https://www.icmarkets.com',
    affiliateUrl: 'https://www.icmarkets.com',
    contactEmail: 'support@icmarkets.com',
    brandColor: '#10b981',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'fbs',
    slug: 'fbs',
    name: 'FBS',
    rankNum: 5,
    rank: '#5',
    isFirst: false,
    rating: 4.6,
    reviewsCount: '4.8K reviews',
    trustScore: 96,
    highlightBadge: '1:3000 Max Leverage • ₹450 Entry',
    badgeTheme: 'amber',
    minDeposit: '₹450 ($5)',
    minDepositINR: 450,
    minDepositUSD: 5,
    spread: 'From 0.5 pips',
    spreadNum: 0.5,
    maxLeverage: '1:3000',
    regulation: 'ASIC, CySEC, FSC',
    regulatorsList: ['ASIC', 'CySEC', 'FSC'],
    platforms: 'MT4, MT5, FBS App',
    platformsList: ['MT4', 'MT5', 'Mobile App'],
    payments: 'UPI, IMPS, NetBanking, Crypto',
    paymentsList: ['UPI', 'NetBanking', 'Crypto'],
    executionType: 'STP / NDD',
    accountTypes: 'Standard, Cent, Micro, Zero Spread',
    features: ['Cent Account for Safe Learning in ₹ INR', 'Highest 1:3000 Leverage in Market', '100% Deposit Bonus for Active Traders', 'Free VPS for Algorithms'],
    pros: ['Cent account allows trading with as little as ₹100', 'Extremely high leverage flexibility', 'Instant UPI deposit & fast payout'],
    cons: ['High leverage can increase liquidation risk', 'Zero spread account has commission per lot'],
    yearFounded: 2009,
    headquarters: 'Cyprus & Belize',
    categories: ['upi-accepted', 'low-deposit', 'high-leverage', 'mt4-mt5'],
    websiteUrl: 'https://www.fbs.com',
    affiliateUrl: 'https://www.fbs.com',
    contactEmail: 'support@fbs.com',
    brandColor: '#15803d',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'hfm',
    slug: 'hfm',
    name: 'HFM (HotForex)',
    rankNum: 6,
    rank: '#6',
    isFirst: false,
    rating: 4.7,
    reviewsCount: '4.2K reviews',
    trustScore: 97,
    highlightBadge: 'Top Swap-Free • 1:2000 Leverage',
    badgeTheme: 'rose',
    minDeposit: '₹450 ($5)',
    minDepositINR: 450,
    minDepositUSD: 5,
    spread: 'From 0.2 pips',
    spreadNum: 0.2,
    maxLeverage: '1:2000',
    regulation: 'FCA, CySEC, FSCA, DFSA',
    regulatorsList: ['FCA', 'CySEC'],
    platforms: 'MT4, MT5, HFM App',
    platformsList: ['MT4', 'MT5', 'Mobile App'],
    payments: 'UPI, NetBanking, Cards, Crypto',
    paymentsList: ['UPI', 'NetBanking', 'Crypto'],
    executionType: 'Market Execution',
    accountTypes: 'Cent, Zero, Pro, Premium',
    features: ['Dedicated INR Indian Currency Accounts', 'Zero Spread on Major Pairs', 'Copy Trading & PAMM Allocation', 'Negative Balance Protection'],
    pros: ['Allows opening base accounts directly in INR', 'Excellent copy trading ecosystem', 'Highly regulated globally with fast UPI'],
    cons: ['Cent account spreads are slightly higher', 'Pro account requires higher turnover'],
    yearFounded: 2010,
    headquarters: 'Cyprus & South Africa',
    categories: ['top-rated', 'upi-accepted', 'low-deposit', 'high-leverage', 'mt4-mt5'],
    websiteUrl: 'https://www.hfm.com',
    affiliateUrl: 'https://www.hfm.com',
    contactEmail: 'support@hfm.com',
    brandColor: '#dc2626',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'deriv',
    slug: 'deriv',
    name: 'Deriv',
    rankNum: 7,
    rank: '#7',
    isFirst: false,
    rating: 4.5,
    reviewsCount: '3.9K reviews',
    trustScore: 96,
    highlightBadge: '24/7 Weekend Trading • Synthetic Indices',
    badgeTheme: 'coral',
    minDeposit: '₹850 ($10)',
    minDepositINR: 850,
    minDepositUSD: 10,
    spread: 'From 0.5 pips',
    spreadNum: 0.5,
    maxLeverage: '1:1000',
    regulation: 'MFSA, VFSC, FSC, BVI',
    regulatorsList: ['FSC', 'FSA'],
    platforms: 'Deriv MT5, Deriv X, Deriv Bot',
    platformsList: ['MT4', 'MT5', 'Deriv Bot', 'Web'],
    payments: 'UPI, P2P Indian Transfer, Crypto, Cards',
    paymentsList: ['UPI', 'Crypto'],
    executionType: 'STP / Proprietary Algorithms',
    accountTypes: 'Standard, Financial, Synthetic',
    features: ['Trade 24/7 Even on Saturday & Sunday', 'Free Automated Bot Builder (Deriv Bot)', 'Local Indian P2P Payout Network', 'Synthetic Volatility Indices (Boom/Crash)'],
    pros: ['Markets never close - trade weekends when Indian markets are shut', 'Deriv P2P allows zero fee INR cashouts', 'No slippage on synthetic indices'],
    cons: ['Synthetic indices differ from real interbank forex', 'No cTrader support'],
    yearFounded: 1999,
    headquarters: 'Malta, Malaysia & UAE',
    categories: ['upi-accepted', 'low-deposit', 'high-leverage', 'mt4-mt5'],
    websiteUrl: 'https://www.deriv.com',
    affiliateUrl: 'https://www.deriv.com',
    contactEmail: 'support@deriv.com',
    brandColor: '#ff444f',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'fxtm',
    slug: 'fxtm',
    name: 'FXTM',
    rankNum: 8,
    rank: '#8',
    isFirst: false,
    rating: 4.5,
    reviewsCount: '3.1K reviews',
    trustScore: 95,
    highlightBadge: 'Local Indian Banking • Low Spread',
    badgeTheme: 'amber',
    minDeposit: '₹850 ($10)',
    minDepositINR: 850,
    minDepositUSD: 10,
    spread: 'From 0.1 pips',
    spreadNum: 0.1,
    maxLeverage: '1:2000',
    regulation: 'FCA, CySEC, FSCA',
    regulatorsList: ['FCA', 'CySEC'],
    platforms: 'MT4, MT5, FXTM Trader',
    platformsList: ['MT4', 'MT5', 'Mobile App'],
    payments: 'UPI, IMPS, Local Bank Wire, Cards',
    paymentsList: ['UPI', 'NetBanking'],
    executionType: 'ECN & STP',
    accountTypes: 'Micro, Advantage, Advantage Plus',
    features: ['Direct Indian NetBanking Deposit Channel', 'Competitive Raw Spread on Advantage Account', 'Copy Trading App with Verified Track Record', 'Zero Commission on Micro Account'],
    pros: ['Smooth local bank transfer deposit channels', 'High leverage tiers available', 'Comprehensive trading education in Hindi & English'],
    cons: ['Withdrawal processing takes up to 24 hours on weekends', 'Standard account spread is average'],
    yearFounded: 2011,
    headquarters: 'London & Cyprus',
    categories: ['upi-accepted', 'low-deposit', 'high-leverage', 'mt4-mt5'],
    websiteUrl: 'https://www.forextime.com',
    affiliateUrl: 'https://www.forextime.com',
    contactEmail: 'support@forextime.com',
    brandColor: '#f97316',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'pepperstone',
    slug: 'pepperstone',
    name: 'Pepperstone',
    rankNum: 9,
    rank: '#9',
    isFirst: false,
    rating: 4.7,
    reviewsCount: '3.4K reviews',
    trustScore: 98,
    highlightBadge: 'Fastest Execution • TradingView Direct',
    badgeTheme: 'purple',
    minDeposit: '₹16,000 ($200)',
    minDepositINR: 16000,
    minDepositUSD: 200,
    spread: 'From 0.0 pips',
    spreadNum: 0.0,
    maxLeverage: '1:500',
    regulation: 'ASIC, FCA, CySEC, BaFin',
    regulatorsList: ['ASIC', 'FCA', 'CySEC'],
    platforms: 'MT4, MT5, cTrader, TradingView',
    platformsList: ['MT4', 'MT5', 'cTrader', 'TradingView'],
    payments: 'UPI, NetBanking, Credit Cards, Crypto',
    paymentsList: ['UPI', 'NetBanking', 'Crypto'],
    executionType: 'ECN / DMA',
    accountTypes: 'Razor, Standard',
    features: ['Direct TradingView Integration', 'Institutional Tier-1 Spreads (0.0 EUR/USD)', 'Sub-30ms Order Latency', 'Tier-1 Regulators (FCA, ASIC, BaFin)'],
    pros: ['Trade directly on TradingView charts with 0.0 spreads', 'Zero requotes and exceptional execution speed', 'Tier-1 regulatory safety'],
    cons: ['Higher minimum initial deposit (₹16,000)', 'Standard account has spread markup'],
    yearFounded: 2010,
    headquarters: 'Melbourne, Australia',
    categories: ['top-rated', 'upi-accepted', 'raw-spread', 'ecn', 'tradingview', 'mt4-mt5'],
    websiteUrl: 'https://www.pepperstone.com',
    affiliateUrl: 'https://www.pepperstone.com',
    contactEmail: 'support@pepperstone.com',
    brandColor: '#2563eb',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'avatrade',
    slug: 'avatrade',
    name: 'AvaTrade',
    rankNum: 10,
    rank: '#10',
    isFirst: false,
    rating: 4.6,
    reviewsCount: '2.8K reviews',
    trustScore: 96,
    highlightBadge: 'AvaProtect Loss Shield • Beginner Friendly',
    badgeTheme: 'blue',
    minDeposit: '₹8,000 ($100)',
    minDepositINR: 8000,
    minDepositUSD: 100,
    spread: 'From 0.9 pips',
    spreadNum: 0.9,
    maxLeverage: '1:400',
    regulation: 'CBI, ASIC, FSA, FSCA',
    regulatorsList: ['ASIC', 'CBI', 'FSA'],
    platforms: 'MT4, MT5, AvaTradeGO',
    platformsList: ['MT4', 'MT5', 'Mobile App'],
    payments: 'UPI, NetBanking, Credit Cards',
    paymentsList: ['UPI', 'NetBanking'],
    executionType: 'Market Maker / Fixed Spreads',
    accountTypes: 'Standard, Islamic, Pro',
    features: ['AvaProtect Hedging Loss Reimbursement Tool', 'Fixed Spreads Available', '6 Global Financial Licenses', 'AvaSocial Community Copying'],
    pros: ['Unique AvaProtect protects capital on high impact news', 'Excellent beginner app experience', 'Safe Irish Central Bank & ASIC regulation'],
    cons: ['Spreads are higher than raw ECN competitors', 'Inactivity fees apply after 3 months'],
    yearFounded: 2006,
    headquarters: 'Dublin, Ireland',
    categories: ['top-rated', 'upi-accepted', 'mt4-mt5'],
    websiteUrl: 'https://www.avatrade.com',
    affiliateUrl: 'https://www.avatrade.com',
    contactEmail: 'support@avatrade.com',
    brandColor: '#0284c7',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'tickmill',
    slug: 'tickmill',
    name: 'Tickmill',
    rankNum: 11,
    rank: '#11',
    isFirst: false,
    rating: 4.5,
    reviewsCount: '2.2K reviews',
    trustScore: 95,
    highlightBadge: 'Lowest Brokerage Commission • 0.0 Pip',
    badgeTheme: 'rose',
    minDeposit: '₹8,000 ($100)',
    minDepositINR: 8000,
    minDepositUSD: 100,
    spread: 'From 0.0 pips',
    spreadNum: 0.0,
    maxLeverage: '1:500',
    regulation: 'FCA, CySEC, FSA',
    regulatorsList: ['FCA', 'CySEC'],
    platforms: 'MT4, MT5, Mobile App',
    platformsList: ['MT4', 'MT5', 'Mobile App'],
    payments: 'UPI, NetBanking, Crypto, Cards',
    paymentsList: ['UPI', 'NetBanking', 'Crypto'],
    executionType: 'True STP / ECN',
    accountTypes: 'Classic, Pro, VIP',
    features: ['Cheapest Commission in Industry ($2/lot per side)', 'No Requotes Guaranteed', 'Free VPS for Trading Bots', 'Autochartist Market Analysis Included'],
    pros: ['Ultra-low commissions save money for high frequency scalpers', 'Tight raw spreads on major pairs', 'Solid FCA regulation'],
    cons: ['Asset selection is focused primarily on FX & commodities', 'Platform features are standard'],
    yearFounded: 2014,
    headquarters: 'London & Seychelles',
    categories: ['upi-accepted', 'raw-spread', 'ecn', 'mt4-mt5'],
    websiteUrl: 'https://www.tickmill.com',
    affiliateUrl: 'https://www.tickmill.com',
    contactEmail: 'support@tickmill.com',
    brandColor: '#e11d48',
    isVerified: true,
    isSeeded: true,
  },
  {
    id: 'oanda',
    slug: 'oanda',
    name: 'OANDA',
    rankNum: 12,
    rank: '#12',
    isFirst: false,
    rating: 4.6,
    reviewsCount: '2.5K reviews',
    trustScore: 99,
    highlightBadge: '₹0 Min. Deposit • 28 Years Trust',
    badgeTheme: 'teal',
    minDeposit: '₹0 ($0)',
    minDepositINR: 0,
    minDepositUSD: 0,
    spread: 'From 0.8 pips',
    spreadNum: 0.8,
    maxLeverage: '1:200',
    regulation: 'CFTC, NFA, FCA, ASIC',
    regulatorsList: ['CFTC', 'NFA', 'FCA', 'ASIC'],
    platforms: 'TradingView, MT4, OANDA App',
    platformsList: ['TradingView', 'MT4', 'Proprietary Web'],
    payments: 'NetBanking, Credit Cards, Bank Wire',
    paymentsList: ['NetBanking', 'Cards'],
    executionType: 'No Dealing Desk (NDD)',
    accountTypes: 'Standard, Core Spread',
    features: ['Zero Minimum Deposit Required', 'Historical Forex Data & Heatmaps', 'Integrated TradingView Chart Engine', 'Tier-1 Regulated Since 1996'],
    pros: ['Start with any amount - zero minimum deposit threshold', '28+ year impeccable regulatory safety history', 'TradingView native integration'],
    cons: ['Local Indian UPI options can require card gateways', 'Lower max leverage than offshore brokers'],
    yearFounded: 1996,
    headquarters: 'New York, USA',
    categories: ['top-rated', 'low-deposit', 'tradingview', 'us-accepted'],
    websiteUrl: 'https://www.oanda.com',
    affiliateUrl: 'https://www.oanda.com',
    contactEmail: 'support@oanda.com',
    brandColor: '#0d9488',
    isVerified: true,
    isSeeded: true,
  },
];
